# -*- coding: utf-8 -*-
"""洛书 LuoShu-512 常量表生成器
输出: luoshu/const_gen.go
  - IV:   18 个 64 位字 = 前 18 个素数平方根小数部分 × 2^64
  - K:   243 个 64 位字 = 前 243 个素数立方根小数部分 × 2^64 (81轮 × 3线)
  - 幻线表 LINES[8]、旋转量表 ROTS[9][2]、投影表 PROJ[8]
纯整数运算（二分求整数平方根/立方根），无浮点误差。
"""
from itertools import combinations

# ---------- 整数根 ----------
def isqrt(n: int) -> int:
    if n < 0: raise ValueError
    if n == 0: return 0
    x = 1 << ((n.bit_length() + 1) // 2)
    while True:
        y = (x + n // x) // 2
        if y >= x: return x
        x = y

def iroot(n: int, k: int) -> int:
    if n < 0: raise ValueError
    if n == 0: return 0
    x = 1 << ((n.bit_length() + k - 1) // k + 1)
    while True:
        d = (n - x ** k) if k == 2 else (n - x * x * x if k == 3 else None)
        t = (x * (k - 1) + n // x ** (k - 1)) // k
        if t >= x: return x if x ** k <= n else x - 1
        x = t

def icbrt(n: int) -> int:
    if n == 0: return 0
    x = 1 << ((n.bit_length() + 2) // 3 + 1)
    while True:
        t = (2 * x + n // (x * x)) // 3
        if t >= x: return x if x ** 3 <= n else x - 1
        x = t

# ---------- 素数 ----------
def primes(count: int):
    ps, n = [], 2
    while len(ps) < count:
        if all(n % p for p in ps if p * p <= n):
            ps.append(n)
        n += 1
    return ps

# ---------- 常量计算（纯整数，可复现） ----------
def sqrt_frac(q: int) -> int:
    # floor(frac(sqrt(q)) * 2^64) = floor(sqrt(q * 2^128)) - floor(sqrt(q)) * 2^64
    return isqrt(q << 128) - isqrt(q) * (1 << 64)

def cbrt_frac(p: int) -> int:
    # floor(frac(cbrt(p)) * 2^64) = floor(cbrt(p * 2^192)) - floor(cbrt(p)) * 2^64
    return icbrt(p << 192) - icbrt(p) * (1 << 64)

IV = [sqrt_frac(q) for q in primes(18)]
K  = [cbrt_frac(p) for p in primes(243)]

# ---------- 结构表 ----------
# 洛书九宫（行优先, 宫0..8）: 宫 i 的洛书数
LUOSHU = [4, 9, 2, 3, 5, 7, 8, 1, 6]

# 旋转量表（机器搜索定稿, 见 rot_search.py）
P = [5, 7, 13, 23, 31, 43, 47, 53, 61]
# 宫 i 双爻: 爻0 = P[(L-1) mod 9], 爻1 = P[(L+3) mod 9]  (错4相位)
ROTS = [(P[(L - 1) % 9], P[(L + 3) % 9]) for L in LUOSHU]

# 幻线表（8条: 3行+3列+2对角, 按宫索引）
# 编号顺序刻意交错线型: R0,C0,R1,C1,R2,C2,DA,DB
LINES = [
    (0, 1, 2),  # 0: 行0
    (0, 3, 6),  # 1: 列0
    (3, 4, 5),  # 2: 行1
    (1, 4, 7),  # 3: 列1
    (6, 7, 8),  # 4: 行2
    (2, 5, 8),  # 5: 列2
    (0, 4, 8),  # 6: 主对角
    (2, 4, 6),  # 7: 反对角
]

# 位置置换 σ = (0 4 8 1 5 2 6 3 7): 每8轮一次, 72轮=9次=σ⁹=恒等
SIGMA = [0] * 9
for a, b in zip([0, 4, 8, 1, 5, 2, 6, 3, 7], [4, 8, 1, 5, 2, 6, 3, 7, 0]):
    SIGMA[a] = b  # σ(a) = b: 轮结束时 x'[σ(a)] = x[a]

# 投影旋转表: 中宫折入 8 个输出字, 用定稿表前8个值
PROJ = P[:8]

# ---------- 自检 ----------
assert len(IV) == 18 and all(0 < v < (1 << 64) for v in IV)
assert len(K) == 243 and all(0 < v < (1 << 64) for v in K)
# 旋转量卫生断言（与 rot_search.py 一致, 进 Go 单测）
for a, b in combinations(P, 2):
    assert a + b != 64, f"互补对 {a},{b}"
for a, b, c in combinations(sorted(P), 3):
    assert a + c != 2 * b, f"等差三元组 {a},{b},{c}"
    assert b % a != 0, f"倍数对 {a},{b}"
s = set(P)
for x in P:
    assert (2 * x) % 64 not in s or (2 * x) % 64 == x
# 置换 σ⁹ = 恒等
perm = list(range(9))
for _ in range(9):
    perm = [SIGMA[perm[i]] for i in range(9)]
assert perm == list(range(9)), "σ⁹ ≠ 恒等!"
# 幻线均为3宫且和=15(洛书幻方性质)
for i, ln in enumerate(LINES):
    assert len(ln) == 3
    assert sum(LUOSHU[j] for j in ln) == 15, f"幻线{i}和≠15"

# ---------- 输出 Go 代码 ----------
def gow(name, vals, per_line=4, comment=""):
    out = [f"// {comment}"] if comment else []
    out.append(f"var {name} = [...]uint64{{")
    for i in range(0, len(vals), per_line):
        chunk = ", ".join(f"0x{v:016X}" for v in vals[i:i + per_line])
        out.append(f"\t{chunk}, // [{i}:{i+len(vals[i:i+per_line])}]")
    out.append("}")
    return "\n".join(out)

go = []
go.append("// Code generated by scripts/gen_consts.py. DO NOT EDIT.")
go.append("// 洛书 LuoShu-512 常量表: 可用同脚本独立复现验证。")
go.append("")
go.append("package luoshu")
go.append("")
go.append(gow("iv", IV, 3, "iv[i] = floor(frac(sqrt(第(i+1)个素数)) × 2^64), 18字 = 9宫×2爻 初始状态"))
go.append("")
go.append(gow("roundK", K, 3, "roundK[i] = floor(frac(cbrt(第(i+1)个素数)) × 2^64), 243 = 81轮×3线"))
go.append("")
go.append("// luoshuNum[i]: 宫i 的洛书数(行优先 4 9 2 / 3 5 7 / 8 1 6)")
go.append("var luoshuNum = [9]int{4, 9, 2, 3, 5, 7, 8, 1, 6}")
go.append("")
go.append("// rotsPal[i] = (爻0旋转量, 爻1旋转量), 由定稿表 P 按洛书数索引+错4相位")
go.append("var rotsPal = [9][2]uint{")
for i, (r0, r1) in enumerate(ROTS):
    go.append(f"\t{{{r0}, {r1}}}, // 宫{i} 洛书数{LUOSHU[i]}")
go.append("}")
go.append("")
go.append("// lines[8]: 8条幻线(3行+3列+2对角), 编号交错线型; 每线和=15")
go.append("var lines = [8][3]int{")
for i, ln in enumerate(LINES):
    go.append(f"\t{{{ln[0]}, {ln[1]}, {ln[2]}}}, // 线{i}: 宫{ln[0]},{ln[1]},{ln[2]}")
go.append("}")
go.append("")
go.append("// sigma[i]: 位置置换σ, x'[σ[i]] = x[i]; 每8轮执行, 72轮=9次=σ⁹=恒等, 每字遍历9宫")
go.append("var sigma = [9]int{" + ", ".join(str(v) for v in SIGMA) + "}")
go.append("")
go.append("// projRot[i]: 终局投影中宫折入旋转量(定稿表前8值)")
go.append("var projRot = [8]uint{" + ", ".join(str(v) for v in PROJ) + "}")

with open("/home/z/my-project/luoshu/const_gen.go", "w", encoding="utf-8") as f:
    f.write("\n".join(go) + "\n")

print("const_gen.go 生成完毕")
print(f"  IV: {len(IV)} 字, 首字 0x{IV[0]:016X} (√2 小数)")
print(f"  K : {len(K)} 字, 首字 0x{K[0]:016X} (∛2 小数), 末字 0x{K[242]:016X}")
print(f"  旋转量表: {P}")
print(f"  σ⁹ = 恒等 ✓, 幻线和=15 ✓, 卫生断言全过 ✓")
