# -*- coding: utf-8 -*-
"""洛书 LuoShu-512 汉字表生成器
输入: /tmp/zhfreq.csv (六亿知乎语料通规汉字字频表, forfudan/chinese-characters-frequency)
输出: luoshu/zhchars.go — 前 2048 高频字 + SHA-256 指纹断言
"""
import hashlib

with open("/tmp/zhfreq.csv", encoding="utf-8") as f:
    rows = [l.strip().split(",") for l in f if l.strip()]

header, data = rows[0], rows[1:]
assert header[0] == "char"
chars = [r[0] for r in data[:2048]]

# 校验
assert len(chars) == 2048, len(chars)
assert len(set(chars)) == 2048, "字表有重复!"
assert all(len(c) == 1 for c in chars), "存在非单字条目"
assert all('\u4e00' <= c <= '\u9fff' for c in chars), "存在非 CJK 基本区字符"

# 指纹（字表冻结的证明）
table_str = "".join(chars)
sha = hashlib.sha256(table_str.encode("utf-8")).hexdigest()

# Go 源码: 每行 64 字, 32 行
lines = [table_str[i:i + 64] for i in range(0, 2048, 64)]
assert len(lines) == 32

go = []
go.append("// Code generated by scripts/gen_zhchars.py. DO NOT EDIT.")
go.append("// 洛书 LuoShu-512 汉字表: 六亿知乎语料字频表前 2048 高频字")
go.append("// 来源: github.com/forfudan/chinese-characters-frequency (通规汉字, 降序)")
go.append("// 表即规范: 任意 2048 字双射安全性等价, 字频排序仅为辨识度")
go.append(f"// 表 SHA-256: {sha}")
go.append("")
go.append("package luoshu")
go.append("")
go.append(f"const zhTableSHA256 = \"{sha}\"")
go.append("")
go.append("// zhTable[i]: 11位索引 i → 汉字; i ∈ [0, 2048)")
go.append("const zhTable = \"\" +")
for i, ln in enumerate(lines):
    suffix = " +" if i < 31 else ""
    go.append(f"\t\"{ln}\"{suffix}")
go.append("")
go.append("// zhIndex[r]: 汉字 r → 11位索引; 启动时由 zhTable 构建")
go.append("var zhIndex map[rune]uint16")

with open("/home/z/my-project/luoshu/zhchars.go", "w", encoding="utf-8") as f:
    f.write("\n".join(go) + "\n")

print("zhchars.go 生成完毕")
print(f"  字数: {len(chars)}, 无重复 ✓, 全部 CJK 基本区 ✓")
print(f"  首字: {chars[0]}, 末字: {chars[-1]}")
print(f"  表 SHA-256 指纹: {sha}")
print(f"  样例: {''.join(chars[1000:1044])}")
